name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.23]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          go build -o git-ez-env.exe
        else
          go build -o git-ez-env
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-ez-env-${{ runner.os }}-${{ runner.arch }}
        path: |
          git-ez-env*
          !*.md

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          git-ez-env-ubuntu-latest-x86_64/git-ez-env
          git-ez-env-macos-latest-x86_64/git-ez-env
          git-ez-env-windows-latest-x86_64/git-ez-env.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 